### PR TITLE
Return bluebird promises

### PR DESCRIPTION
**Pull request by scull7**
- Make sure that all the exported methods return a bluebird promise.

### CODE REVIEW

**Comment by jxbadam** [comment]
Checks Failed 👎

**Review by jonajonlee — APPROVED** [review]
:shipit:

**Comment by scull7** [comment]
I have no idea what this is talking about code coverage increases with this merge 98.08% -> 98.19%

**Comment by scull7** [comment]
CodeCov.io is whining about the code coverage in the patch itself since I didn't cover the driver error throw.

**Review by Bellk17 — APPROVED** [review]
:shipit:

**Pull request merged**
